version: '3'
services:
  telimongo:
    image: mongo:latest
    container_name: telimongo
    volumes:
      - newdata:/data/db
        #- mongo-data10:/data/db
    networks:
      - teli
    restart: always
  teliapi:
    image: hrmj/teliapi
    container_name: teliapi
    depends_on:
      - telimongo
    ports:
      - "3000:3000"
    volumes:
      - ../tekstitliikkeessa_api:/opt/api
      - wwwroot:/wwwroot
    networks:
      - teli
    restart: always
  telinginx:
    image: hrmj/telinginx
    container_name: telinginx
    ports:
      - "8000:8000"
    volumes:
      - ../tekstitliikkeessa_frontend/dist:/usr/share/nginx/html/
      - wwwroot:/wwwroot
    tty: true
    networks:
      - teli
    restart: always
volumes:
  newdata:
    driver: local
  mongo-data10:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/juho_harme/restore/data/db/
  data:
    driver: local
  wwwroot:
    driver: local
networks:
  teli:

