version: '2'
services:
  telimongo:
    image: mongo:bionic
    container_name: telimongo
    volumes:
      - data:/data
    networks:
      - teli
    restart: always
  teliapi:
    image: hrmj/teliapi
    container_name: teliapi
    ports:
      - "3000:3000"
    volumes:
      - wwwroot:/wwwroot
    env_file: .env
    networks:
      - teli
    restart: always
  telinginx:
    image: hrmj/telinginx
    container_name: telinginx
    ports:
      - "8000:8000"
    volumes:
      - wwwroot:/wwwroot
    tty: true
    networks:
      - teli
    restart: always
volumes:
  data:
    driver: local
  wwwroot:
    driver: local
networks:
  teli:

