version: '2'
services:
  telimongo:
    image: mongo:bionic
    container_name: telimongo
    volumes:
      - data:/data
    networks:
      - teli
  teliapi:
    image: hrmj/teliapi
    container_name: teliapi
    ports:
      - "3000:3000"
    volumes:
      - wwwroot:/wwwroot
    env_file: .env
    networks:
      - teli
volumes:
  data:
    driver: local
  wwwroot:
    driver: local
networks:
  teli:

