version: '2'
services:
  telimongo:
    image: mongo:bionic
    container_name: telimongo
    volumes:
      - data:/data
    networks:
      - teli
    restart: always
  teliapi:
    build:
      context: ../
      dockerfile: containers/api/Dockerfile.prod
    container_name: teliapi
    depends_on:
      - telimongo
    ports:
      - "3000:3000"
    volumes:
      - ../tekstitliikkeessa_api:/opt/api
      - wwwroot:/wwwroot
    networks:
      - teli
    restart: always
  telinginx:
    build:
      context: ../
      dockerfile: containers/telinginx/Dockerfile
    container_name: telinginx
    ports:
      - "8000:8000"
    volumes:
      - ../tekstitliikkeessa_frontend/dist:/usr/share/nginx/html/
      - wwwroot:/wwwroot
    tty: true
    networks:
      - teli
    restart: always
volumes:
  data:
    driver: local
  wwwroot:
    driver: local
networks:
  teli:

