version: '2'
services:
  telimongo:
    image: mongo:bionic
    container_name: telimongo
    volumes:
      - data:/data
    networks:
      - teli
  teliapi:
    build:
      context: ./
      dockerfile: api/Dockerfile.prod
    image: teliapi
    container_name: teliapi
    ports:
      - "3000:3000"
    volumes:
      - ../tekstitliikkeessa_api:/home/developer/project
      - wwwroot:/wwwroot
    networks:
      - teli
  telinginx:
    build:
      context: ./telinginx
      dockerfile: Dockerfile
    image: telinginx
    container_name: telinginx
    ports:
      - "8000:8000"
    volumes:
      - ../tekstitliikkeessa_frontend/dist:/usr/share/nginx/html/
      - wwwroot:/wwwroot
    tty: true
    networks:
      - teli
volumes:
  data:
    driver: local
  wwwroot:
    driver: local
networks:
  teli:

