FROM node:16

WORKDIR /usr/src/app

#RUN apt update && apt install curl gnupg software-properties-common -y &&\
#    rm -rf /var/lib/apt/lists/*
#
#RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
#    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list 
#
#RUN curl  https://install-node.now.sh/10 -o node.sh 
#RUN bash node.sh --yes 
#RUN apt update && apt install -y yarn &&\
#    rm -rf /var/lib/apt/lists/*

#RUN yarn
CMD yarn start
